apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postres-pod
    app: demo-voting-app
spec:
  container:
    - name: postres
      image: postgres
      ports:
        - containerPort: 5432
      env:
	- name: "POSTGRES_USER"
	  value: "postgres"
	- name: "POSTGRES_PASSWORD"
	  value: "postgres"
